[package]
name = "second"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ghost-cell = "0.2.2"
static-rc = { version = "0.6.0", features = ["compile-time-ratio"] }