[package]
name = "fourth"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ghost-cell = "0.2.2"
slotmap = "1.0.6"
typed-arena = "2.0.1"

